<script lang="ts" setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { Page } from '@vben/common-ui';
import { Button, Card, Checkbox, Form, FormItem, Input, Modal, Select, SelectOption, Space, Table, Tag, message } from 'ant-design-vue';
import { enterpriseApi } from '#/api';

const loading=ref(false),saving=ref(false),roles=ref<any[]>([]),permissions=ref<Array<{label:string;value:string}>>([]),users=ref<any[]>([]),campuses=ref<any[]>([]),classrooms=ref<any[]>([]),organization=ref<any>({});
const roleVisible=ref(false),permissionVisible=ref(false),bindingVisible=ref(false),selectedRole=ref<any>(null),selectedPermissions=ref<string[]>([]);
const roleForm=reactive({code:'',name:'',description:'',dataScope:'organization',permissions:[] as string[]});
const bindingForm=reactive({userId:'',roleId:'',scopeId:''});
const columns=[{title:'角色',dataIndex:'name'},{title:'编码',dataIndex:'code'},{title:'数据范围',dataIndex:'data_scope'},{title:'权限数',dataIndex:'permissions'},{title:'已授权用户',dataIndex:'binding_count'},{title:'类型',dataIndex:'is_system'},{title:'操作',key:'actions'}];
const bindingRole=computed(()=>roles.value.find(item=>item.id===bindingForm.roleId));
const scopeOptions=computed(()=>{const role=bindingRole.value;if(!role)return[];if(role.data_scope==='organization')return[{id:organization.value.id,name:organization.value.name}];if(role.data_scope==='campus')return campuses.value;if(role.data_scope==='classroom')return classrooms.value;return[];});
function scopeLabel(value:string){return({organization:'全组织',campus:'指定校区',classroom:'指定教室',self:'本人'} as Record<string,string>)[value]||value;}
const permissionLabels:Record<string,string>={
  'organization.read':'查看组织资料','organization.manage':'管理组织资料','campus.read':'查看校区','campus.manage':'管理校区',
  'user.read':'查看用户','user.manage':'管理用户','role.read':'查看角色权限','role.manage':'管理角色权限',
  'classroom.read':'查看教室','classroom.manage':'管理教室','device.read':'查看设备','device.manage':'管理设备',
  'content.read':'查看教学内容','content.manage':'管理教学内容','audit.read':'查看安全审计','audit.export':'导出安全审计',
  'operations.read':'查看运营状态','operations.manage':'管理运营操作',
};
function permissionLabel(value:string){return permissionLabels[value]||value;}
async function load(){loading.value=true;try{const[r,p,u,c,cl,o]=await Promise.all([enterpriseApi.roles(),enterpriseApi.permissions(),enterpriseApi.users(),enterpriseApi.campuses(),enterpriseApi.classrooms(),enterpriseApi.organization()]);roles.value=r;permissions.value=p.map((value:string)=>({label:`${permissionLabel(value)}（${value}）`,value}));users.value=u.items;campuses.value=c;classrooms.value=cl;organization.value=o;}finally{loading.value=false;}}
function openCreate(){Object.assign(roleForm,{code:'',name:'',description:'',dataScope:'organization',permissions:[]});roleVisible.value=true;}
async function createRole(){if(!roleForm.code.trim()||!roleForm.name.trim()){message.warning('请填写角色名称和编码');return;}saving.value=true;try{await enterpriseApi.createRole({...roleForm,code:roleForm.code.trim(),name:roleForm.name.trim()});message.success('角色已创建');roleVisible.value=false;await load();}finally{saving.value=false;}}
function openPermissions(role:any){selectedRole.value=role;selectedPermissions.value=[...role.permissions];permissionVisible.value=true;}
async function persistPermissions(){saving.value=true;try{await enterpriseApi.setRolePermissions(selectedRole.value.id,selectedPermissions.value);message.success('角色权限已更新，相关用户会话将失效');permissionVisible.value=false;await load();}finally{saving.value=false;}}
function savePermissions(){const before=new Set<string>(selectedRole.value.permissions||[]),after=new Set(selectedPermissions.value);const added=[...after].filter(value=>!before.has(value)),removed=[...before].filter(value=>!after.has(value));if(!added.length&&!removed.length){permissionVisible.value=false;return;}Modal.confirm({title:`确认更新“${selectedRole.value.name}”的权限？`,content:`新增 ${added.length} 项${added.length?`：${added.map(permissionLabel).join('、')}`:''}；移除 ${removed.length} 项${removed.length?`：${removed.map(permissionLabel).join('、')}`:''}。保存后相关用户需要重新登录。`,okText:'确认更新',cancelText:'取消',onOk:persistPermissions});}
function openBinding(role?:any){Object.assign(bindingForm,{userId:'',roleId:role?.id||'',scopeId:''});if(role?.data_scope==='organization')bindingForm.scopeId=organization.value.id;bindingVisible.value=true;}
function roleChanged(){bindingForm.scopeId=bindingRole.value?.data_scope==='organization'?organization.value.id:'';}
async function bind(){const role=bindingRole.value;if(!role||!bindingForm.userId||!bindingForm.scopeId){message.warning('请选择用户、角色和授权范围');return;}saving.value=true;try{await enterpriseApi.bindRole(bindingForm.userId,{roleId:role.id,scopeType:role.data_scope,scopeId:bindingForm.scopeId});message.success('角色授权成功，用户需要重新登录');bindingVisible.value=false;await load();}finally{saving.value=false;}}
onMounted(load);
</script>
<template><Page title="角色与权限" description="以 RBAC 权限和组织、校区、教室数据范围控制后台访问"><Card><div class="mb-4 flex justify-end gap-2"><Button @click="openBinding()">给用户授权</Button><Button type="primary" @click="openCreate">新建角色</Button></div><Table row-key="id" :columns="columns" :data-source="roles" :loading="loading"><template #bodyCell="{column,record,text}"><template v-if="column.dataIndex==='permissions'">{{text.length}} 项</template><Tag v-else-if="column.dataIndex==='data_scope'" color="blue">{{scopeLabel(text)}}</Tag><Tag v-else-if="column.dataIndex==='is_system'" :color="text?'purple':'default'">{{text?'系统角色':'自定义'}}</Tag><Space v-else-if="column.key==='actions'"><Button type="link" :disabled="record.code==='organization_owner'" @click="openPermissions(record)">配置权限</Button><Button type="link" @click="openBinding(record)">授权用户</Button></Space></template></Table></Card><Modal v-model:open="roleVisible" title="新建角色" width="720px" :confirm-loading="saving" @ok="createRole"><Form layout="vertical"><FormItem label="角色名称" required><Input v-model:value="roleForm.name"/></FormItem><FormItem label="角色编码" required><Input v-model:value="roleForm.code" placeholder="例如 grade_manager"/></FormItem><FormItem label="说明"><Input.TextArea v-model:value="roleForm.description"/></FormItem><FormItem label="数据范围"><Select v-model:value="roleForm.dataScope"><SelectOption value="organization">全组织</SelectOption><SelectOption value="campus">指定校区</SelectOption><SelectOption value="classroom">指定教室</SelectOption></Select></FormItem><FormItem label="权限"><Checkbox.Group v-model:value="roleForm.permissions" :options="permissions"/></FormItem></Form></Modal><Modal v-model:open="permissionVisible" :title="`配置权限：${selectedRole?.name||''}`" width="760px" :confirm-loading="saving" @ok="savePermissions"><Checkbox.Group v-model:value="selectedPermissions" :options="permissions" class="grid grid-cols-2 gap-3"/></Modal><Modal v-model:open="bindingVisible" title="给用户授权" :confirm-loading="saving" @ok="bind"><Form layout="vertical"><FormItem label="用户" required><Select v-model:value="bindingForm.userId" show-search option-filter-prop="label"><SelectOption v-for="user in users" :key="user.id" :value="user.id" :label="`${user.name} (${user.login_name})`">{{user.name}}（{{user.login_name}}）</SelectOption></Select></FormItem><FormItem label="角色" required><Select v-model:value="bindingForm.roleId" @change="roleChanged"><SelectOption v-for="role in roles.filter(item=>item.data_scope!=='self')" :key="role.id" :value="role.id">{{role.name}}</SelectOption></Select></FormItem><FormItem label="授权范围" required><Select v-model:value="bindingForm.scopeId"><SelectOption v-for="item in scopeOptions" :key="item.id" :value="item.id">{{item.name}}</SelectOption></Select></FormItem></Form></Modal></Page></template>
