const socket = require('../../utils/socket');
const roomContext = require('../../utils/room-context');
const { sessionStore } = require('../../utils/session');
const { parseStudentNames } = require('../../utils/student-list');

function teacherView(item, currentId) {
  const id = item.connection_id || '';
  const subjects = item.subjects || [];
  return { ...item, id, avatar:String(item.name||'教').slice(0,1),isSelf:id===currentId,isHomeroom:item.role==='班主任',subjectValue:subjects.join('、'),subjectText:subjects.join('、') || '尚未设置授课科目',shortId:id.slice(-8) };
}

Page({
  data:{tab:'students',status:'connecting',statusText:'正在连接教室',className:'',students:[],approvedTeachers:[],pendingTeachers:[],pendingFaces:[],studentNames:[],saving:false,onboarding:false,onboardingStep:1,batchVisible:false,batchText:'',batchCount:0},
  onLoad(options){this.guideRequested=options.guide==='1';const result=roomContext.activateByCode(options.code);if(!result){wx.showToast({title:'教室不存在',icon:'none'});wx.navigateBack();return;}this.room=result.room;this.account=result.session.account;socket.connect(this.room,this.account,{force:true});this.unsubscribe=socket.subscribe((event,payload)=>{if(event==='status')this.setData({status:payload.status,statusText:payload.message});else if(event==='sync')this.applySync(payload);else if(event==='pendingFaces')this.applyFaces(payload.faces||[]);else if(event==='error')wx.showToast({title:payload.message||'操作失败',icon:'none'});});},
  onUnload(){if(this.unsubscribe)this.unsubscribe();},
  applySync(data){if(!data.teacher||data.teacher.role!=='班主任'){wx.showModal({title:'无权访问',content:'只有该教室的班主任可以修改教室设置。',showCancel:false,success:()=>wx.navigateBack()});return;}const needsSetup=data.classroomConfigured===false;const wasOnboarding=this.data.onboarding;this.currentTeacherId=data.teacher.connectionId;if(!this.hasInitialSync){this.hasInitialSync=true;this.setData({className:data.className||this.room.name||'',students:(data.students||[]).map(item=>({...item})),studentNames:(data.students||[]).map(item=>item.name)});}this.setData({onboarding:needsSetup,approvedTeachers:((data.teachers&&data.teachers.approved)||[]).map(item=>teacherView(item,this.currentTeacherId)),pendingTeachers:((data.teachers&&data.teachers.pending)||[]).map(item=>teacherView(item,this.currentTeacherId))});if(needsSetup&&!this.alertEnabled){this.alertEnabled=true;if(wx.enableAlertBeforeUnload)wx.enableAlertBeforeUnload({message:'完成班级基础配置后才能开始使用教室。'});}if(wasOnboarding&&!needsSetup&&this.awaitingSetupSave){this.awaitingSetupSave=false;this.alertEnabled=false;if(wx.disableAlertBeforeUnload)wx.disableAlertBeforeUnload();wx.showModal({title:'教室配置完成',content:'班级名称和学生名单已经保存，现在可以开始使用全部教学功能。',showCancel:false,confirmText:'进入首页',success:()=>wx.switchTab({url:'/pages/home/index'})});}this.applyFaces(data.pendingFaces||[]);},
  applyFaces(faces){this.setData({pendingFaces:(faces||[]).filter(item=>/^data:image\//.test(item.cropBase64||'')).map(item=>({...item,image:item.cropBase64}))});},
  switchTab(event){this.setData({tab:event.currentTarget.dataset.tab});},
  noop(){},
  onClassNameInput(event){this.setData({className:event.detail.value});},
  onStudentInput(event){const students=this.data.students.slice();students[Number(event.currentTarget.dataset.index)]={...students[Number(event.currentTarget.dataset.index)],name:event.detail.value};this.setData({students});},
  addStudent(){this.setData({students:this.data.students.concat({id:`s${Date.now().toString(36)}`,name:''})});},
  openBatch(){this.setData({batchVisible:true,batchText:'',batchCount:0});},
  closeBatch(){this.setData({batchVisible:false,batchText:'',batchCount:0});},
  onBatchInput(event){const batchText=event.detail.value;this.setData({batchText,batchCount:parseStudentNames(batchText).length});},
  applyBatch(){const names=parseStudentNames(this.data.batchText);if(!names.length){wx.showToast({title:'请先粘贴学生名单',icon:'none'});return;}const existingNames=new Set(this.data.students.map(item=>String(item.name||'').trim()).filter(Boolean));const additions=names.filter(name=>!existingNames.has(name)).map((name,index)=>({id:`s${Date.now().toString(36)}${index}`,name}));this.setData({students:this.data.students.filter(item=>String(item.name||'').trim()).concat(additions),batchVisible:false,batchText:'',batchCount:0});wx.showToast({title:`已添加 ${additions.length} 人`,icon:'none'});},
  nextSetupStep(){const className=this.data.className.trim();if(!className){wx.showToast({title:'请填写班级名称',icon:'none'});return;}this.setData({onboardingStep:2});},
  previousSetupStep(){this.setData({onboardingStep:1});},
  completeSetup(){const names=parseStudentNames(this.data.batchText);const students=names.map((name,index)=>({id:`s${Date.now().toString(36)}${index}`,name}));if(!students.length){wx.showToast({title:'请至少录入一名学生',icon:'none'});return;}this.setData({students,studentNames:names});this.submitClassroom(this.data.className.trim(),students,true);},
  removeStudent(event){const index=Number(event.currentTarget.dataset.index);const student=this.data.students[index];wx.showModal({title:'移除学生',content:`确定从名单中移除“${student.name||'未命名学生'}”吗？相关作业提交记录也会一并移除。`,confirmColor:'#FA5151',success:result=>{if(result.confirm)this.setData({students:this.data.students.filter((_item,i)=>i!==index)});}});},
  submitClassroom(className,students,isSetup){const session=sessionStore.load();const activeRoom=session&&session.activeRoom;const subjects=(activeRoom&&activeRoom.subjects)||[];if(!subjects.length){wx.showToast({title:'请先返回首页设置授课科目',icon:'none'});return;}if(!socket.send({type:'update-classroom',classroom:{className,students,subjects}})){wx.showToast({title:'教室连接已断开',icon:'none'});return;}if(isSetup)this.awaitingSetupSave=true;this.setData({saving:true});setTimeout(()=>this.setData({saving:false}),1000);if(!isSetup)wx.showToast({title:'已保存',icon:'success'});},
  saveClassroom(){const className=this.data.className.trim();const students=this.data.students.map(item=>({...item,name:String(item.name||'').trim()})).filter(item=>item.name);if(!className){wx.showToast({title:'请填写班级名称',icon:'none'});return;}if(!students.length){wx.showToast({title:'请至少保留一名学生',icon:'none'});return;}if(new Set(students.map(item=>item.name)).size!==students.length){wx.showToast({title:'学生姓名不能重复',icon:'none'});return;}this.submitClassroom(className,students,false);},
  manageTeacher(event){const {action,id,name}=event.currentTarget.dataset;const actionText={approve:'批准',reject:'拒绝',remove:'移除'}[action];if(!actionText)return;wx.showModal({title:`${actionText}教师`,content:`确定${actionText}“${name}”吗？${action==='approve'?'审批后将同时保存该教师申请时填写的授课科目。':''}`,confirmColor:action==='approve'?'#07C160':'#FA5151',success:result=>{if(result.confirm)socket.send({type:'manage-teacher',action,connectionId:id,subjects:[]});}});},
  editSubjects(event){const {id,name,subjects}=event.currentTarget.dataset;wx.showModal({title:`设置${name}的授课科目`,content:`当前：${subjects||'未设置'}。多个科目请用逗号分隔，每位教师至少保留一个科目。`,editable:true,placeholderText:'例如：语文、道德与法治',success:result=>{if(!result.confirm)return;const values=String(result.content||'').split(/[,，、\s]+/).map(value=>value.trim()).filter(Boolean);if(!values.length){wx.showToast({title:'请至少填写一个科目',icon:'none'});return;}socket.send({type:'manage-teacher',action:'update',connectionId:id,subjects:values});}});},
  matchFace(event){const face=this.data.pendingFaces[Number(event.currentTarget.dataset.index)];const student=this.data.students[Number(event.detail.value)];if(!face||!student)return;wx.showModal({title:'确认人脸匹配',content:`将这张人脸匹配为“${student.name}”？确认后会写入教室人脸库。`,success:result=>{if(result.confirm)socket.send({type:'label-face',faceId:face.faceId,studentId:student.id,name:student.name});}});},
  previewFace(event){const image=event.currentTarget.dataset.image;if(image)wx.previewImage({current:image,urls:[image]});},
});
