(function () {
  'use strict';
  let activeDialog = null;
  let showingGlobalError = false;
  function text(value) { return String(value == null ? '' : value).trim(); }
  function redact(value) { return text(value).replace(/((?:password|passwd|token|secret|api[_-]?key|connection[_-]?key)\s*[:=]\s*)[^\s,;&]+/gi,'$1[已隐藏]').replace(/(Bearer\s+)[A-Za-z0-9._~+\/-]+/gi,'$1[已隐藏]'); }
  function details(error) {
    if (!error) return '未提供底层错误信息';
    if (typeof error === 'string') return redact(error);
    const lines = [redact(error.message || error.errMsg || error.reason || error)].filter(Boolean);
    if (error.code) lines.push(`错误代码：${redact(error.code)}`);
    if (error.status || error.statusCode) lines.push(`状态码：${error.status || error.statusCode}`);
    if (error.stack) lines.push(redact(error.stack));
    return lines.join('\n') || '未知错误';
  }
  function buildReport(options) {
    const now = new Date();
    const suggestions = Array.isArray(options.suggestions) ? options.suggestions.filter(Boolean) : [];
    return ['班达错误报告（教室端）', `发生时间：${now.toLocaleString('zh-CN')} (${now.toISOString()})`, `错误场景：${text(options.context) || document.title || '教室端运行'}`, `错误标题：${text(options.title) || '操作失败'}`, `页面：${location.pathname}`, `系统信息：${navigator.userAgent}`, '', '详细信息：', details(options.error || options.detail), suggestions.length ? `\n建议检查：\n${suggestions.map((item,index)=>`${index+1}. ${item}`).join('\n')}` : ''].filter(Boolean).join('\n');
  }
  function ensureStyle() {
    if (document.getElementById('clientErrorReporterStyle')) return;
    const style=document.createElement('style'); style.id='clientErrorReporterStyle'; style.textContent=`.client-error-overlay{position:fixed;inset:0;z-index:2147483647;display:flex;align-items:center;justify-content:center;padding:22px;background:rgba(8,13,24,.52);backdrop-filter:blur(8px)}.client-error-card{width:min(620px,calc(100vw - 36px));max-height:calc(100vh - 36px);overflow:auto;padding:24px;border:1px solid #dbe3ef;border-radius:18px;color:#172033;background:#fff;box-shadow:0 24px 70px rgba(0,0,0,.28);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.client-error-head{display:flex;align-items:flex-start;gap:13px}.client-error-mark{display:grid;width:44px;height:44px;flex:0 0 44px;place-items:center;border-radius:13px;color:#fff;background:#e5484d;font-size:22px;font-weight:800}.client-error-head h2{margin:0;font-size:20px}.client-error-head p{margin:5px 0 0;color:#667085;font-size:13px;line-height:1.55}.client-error-guide{margin-top:17px;padding:13px 14px;border-radius:11px;color:#667085;background:#fff6e6;font-size:12px;line-height:1.65}.client-error-guide strong{display:block;color:#172033}.client-error-guide ol{margin:7px 0 0;padding-left:20px}.client-error-detail{margin-top:14px}.client-error-detail summary{cursor:pointer;color:#52647e;font-size:12px;font-weight:700}.client-error-detail pre{max-height:220px;overflow:auto;margin:9px 0 0;padding:13px;border-radius:10px;color:#24314a;background:#f3f6fa;font:11px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;word-break:break-word}.client-error-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:19px}.client-error-actions button{min-height:40px;padding:0 16px;border:1px solid #d5dce8;border-radius:9px;color:#25324a;background:#fff;font-size:12px;font-weight:700}.client-error-actions .client-error-copy{color:#fff;border-color:#3568e8;background:#3568e8}.client-error-copy.is-copied{border-color:#20a464;background:#20a464}`; document.head.appendChild(style);
  }
  async function copyReport(report,button){try{if(window.api&&typeof window.api.copyText==='function')await window.api.copyText(report);else await navigator.clipboard.writeText(report);button.textContent='已复制，请提交管理员';button.classList.add('is-copied');}catch(_error){button.textContent='复制失败，请手动复制';}}
  function show(options){options=options||{};const report=buildReport(options);if((innerWidth<440||innerHeight<360)&&window.api&&typeof window.api.showClientError==='function'){window.api.showClientError({title:text(options.title)||'教室端错误',message:text(options.message)||details(options.error||options.detail).split('\n')[0],report});return report;}ensureStyle();if(activeDialog)activeDialog.remove();const overlay=document.createElement('div');overlay.className='client-error-overlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');const card=document.createElement('section');card.className='client-error-card';const head=document.createElement('div');head.className='client-error-head';const mark=document.createElement('span');mark.className='client-error-mark';mark.textContent='!';const copy=document.createElement('div');const title=document.createElement('h2');title.textContent=text(options.title)||'操作失败';const message=document.createElement('p');message.textContent=text(options.message)||details(options.error||options.detail).split('\n')[0];copy.append(title,message);head.append(mark,copy);const guide=document.createElement('div');guide.className='client-error-guide';guide.innerHTML='<strong>请将错误信息提交给管理员</strong>点击下方“复制错误信息”，把复制的完整内容发送给系统管理员，以便快速定位问题。';if(Array.isArray(options.suggestions)&&options.suggestions.length){const list=document.createElement('ol');options.suggestions.forEach(item=>{const li=document.createElement('li');li.textContent=item;list.appendChild(li);});guide.appendChild(list);}const detail=document.createElement('details');detail.className='client-error-detail';const summary=document.createElement('summary');summary.textContent='查看完整错误详情';const pre=document.createElement('pre');pre.textContent=report;detail.append(summary,pre);const actions=document.createElement('div');actions.className='client-error-actions';const close=document.createElement('button');close.type='button';close.textContent='关闭';const copyButton=document.createElement('button');copyButton.type='button';copyButton.className='client-error-copy';copyButton.textContent='复制错误信息';close.onclick=()=>{overlay.remove();activeDialog=null;};copyButton.onclick=()=>copyReport(report,copyButton);actions.append(close,copyButton);card.append(head,guide,detail,actions);overlay.appendChild(card);document.body.appendChild(overlay);activeDialog=overlay;copyButton.focus();return report;}
  window.clientErrors={show,buildReport};
  window.addEventListener('error',event=>{if(showingGlobalError)return;showingGlobalError=true;show({title:'教室端发生运行错误',message:'软件遇到未预期的问题，部分功能可能暂时不可用。',context:document.title,error:event.error||event.message,suggestions:['重试刚才的操作','如果问题重复出现，请复制错误信息并提交给管理员']});setTimeout(()=>{showingGlobalError=false;},0);});
  window.addEventListener('unhandledrejection',event=>{if(showingGlobalError)return;showingGlobalError=true;show({title:'教室端请求处理失败',message:'请求没有正常完成，请检查教室端运行和网络状态。',context:document.title,error:event.reason,suggestions:['检查教室端网络与磁盘空间','稍后重试；若仍失败，请复制错误信息提交管理员']});setTimeout(()=>{showingGlobalError=false;},0);});
})();
